/*
 * XYZWriter.cpp
 *
 *  Created on: 01.03.2010
 *      Author: eckhardw
 */

#include "XYZWriter.h"

#include <iomanip>
#include <sstream>
#include <utility>

namespace md::io {
    XYZWriter::XYZWriter(std::string fileName, const bool allow_delete)
        : OutputWriterBase(std::move(fileName), allow_delete) {}
    XYZWriter::~XYZWriter() = default;

    void XYZWriter::plot_particles(const env::Environment& env, int iteration) {
        std::ofstream file;
        std::stringstream strstr;

        strstr << "output" << '/';
        strstr << file_name << "_" << std::setfill('0') << std::setw(4) << iteration << ".xyz";

        file.open(strstr.str().c_str());
        file << env.size() << std::endl;
        file << "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for "
                "file format doku."
             << std::endl;

        for (auto& particle : env.particles()) {
            std::array<double, 3> x = particle.position;
            file << "Ar ";
            file.setf(std::ios_base::showpoint);

            for (auto& xi : x) {
                file << xi << " ";
            }

            file << std::endl;
        }

        file.close();
    }
}  // namespace md::io
