---
name: Continuous Integration

on:
  push:
  pull_request:
    branches: [main]


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        run: sudo apt-get install -y cmake

      - name: Install Xercescs
        run: sudo apt-get install libxerces-c-dev

      - name: Build and Run
        run: |
            mkdir build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-fopenmp"
            make
            ./MolSim ../input/others/CI_simulation.xml VTK -f

  googletests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        run: sudo apt-get install -y cmake

      - name: Install Xercescs
        run: sudo apt-get install libxerces-c-dev

      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_CXX_FLAGS="-fopenmp"
          make
          ctest --output-on-failure