name: Continuous Integration

on:
  push:
  pull_request:
    branches: [main]


jobs:
  # TODO: Integrate Google Tests

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        run: sudo apt-get install -y cmake

      - name: Install Xercescs
        run: sudo apt-get install libxerces-c-dev

      - name: Build
        run: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug ..
            make


  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}