---
name: Continuous Integration

on:
  push:
  pull_request:
    branches: [main]


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        run: sudo apt-get install -y cmake

      - name: Install Xercescs
        run: sudo apt-get install libxerces-c-dev

      - name: Build and Run
        run: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug ..
            make
            ./MolSim ../input/eingabe-sonne.txt 100 0.1 10 VTK -f
            ./MolSim ../input/assignment2.txt 100 0.1 10 VTK -f

  googletests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        run: sudo apt-get install -y cmake

      - name: Install Xercescs
        run: sudo apt-get install libxerces-c-dev

      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure

  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v7.1.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}